name: agenda_front
description: "Sistema de Gestion de Agendamientos"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  form_builder_extra_fields: ^10.1.0
  form_builder_image_picker: ^4.0.0
  form_builder_validators: ^9.1.0
  internet_file: ^1.2.0
  intl: ^0.18.1
  pdfx: ^2.6.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  vexana: ^3.5.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
